export const SYSTEM_ROLES = [
  "SYSTEM_ADMIN",
  "SCIENTIFIC_MANAGEMENT_HEAD",
  "SCIENTIFIC_MANAGEMENT_STAFF",
  "LEADERSHIP_APPROVAL_AUTHORITY",
  "RESEARCH_OVERSIGHT_AUTHORITY",
  "RESEARCHER_INTERNAL_USER",
  "EXTERNAL_RESEARCHER_USER"
];
